stages:
  - test
  
test-scripts:
  stage: test
  image: koalaman/shellcheck-alpine
  script: shellcheck ./scripts/*.sh
  
test-docker-compose:
  stage: test
  image: 
    name: docker/compose:1.23.0
    entrypoint: [""]
  
  script:
    - docker-compose config