stages:
  - test
  
test-scripts:
  stage: test
  image: koalaman/shellcheck
  script: for file in $(find path/to/scripts -type f); do shellcheck --format=gcc $file; done;
  
test-docker-compose:
  stage: test
  image: docker/compose:1.23.0
  entrypoint: [""]
  
  script:
    - docker-compose config